create table facilities (
id int8 generated by default as identity,
name varchar(255),
price int4,
primary key (id)
);

create table schedules (
id int8 generated by default as identity,
free boolean,
time time,
facility_id int8,
user_id int8,
primary key (id)
);

create table usr (
id int8 generated by default as identity,
automobile varchar(255),
password varchar(255),
role varchar(255),
status varchar(255),
username varchar(255),
primary key (id)
);

alter table if exists schedules
add constraint schedule_facility_fk
foreign key (facility_id) references facilities;

alter table if exists schedules
add constraint schedule_user_fk
foreign key (user_id) references usr;